### ISSUE TITLE
App crashing on api level 28.

### ISSUE THREAD

**Issue by s3rius** [google-udacity-india-scholars/abnd-track-pomodoro-timer-app#53]
### Steps to reproduce

*  Run app on devise with api level 28.
*  Click on "Start pomodoro" button.

### Expected behaviour

Timer starts correctly.

### Actual behaviour

app crashes when "start pomodoro" button is clicked.

![deepin-screen-recorder_select area_20181117010742](https://user-images.githubusercontent.com/18153319/48647398-40efe600-ea05-11e8-952c-33d0e1a5a2f8.gif)

### Java error stack trace

```
java.lang.RuntimeException: Unable to start service gis2018.udacity.pomodoro.CountDownTimerService@660e9de with Intent { cmp=gis2018.udacity.pomodoro/.CountDownTimerService (has extras) }: java.lang.SecurityException: Permission Denial: startForeground from pid=8449, uid=10086 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=8449, uid=10086 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5198)
        at android.app.Service.startForeground(Service.java:695)
        at gis2018.udacity.pomodoro.CountDownTimerService.onStartCommand(CountDownTimerService.java:74)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9189)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1189)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:870)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20437)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:976)
```

### Possible fix

It can be fixed by adding permissions for foreground services in manifest.xml.
And i would like to fix it.

**Comment by s3rius** [comment]
Issue was fixed in commit a0cd7046.

**Comment by numerative** [comment]
Thanks for finding and fixing the bug. Please do open a pull request so that we can merge your changes.

**Comment by piedcipher** [comment]
I'm using the app on mobile running Oreo, and I don't face this issue.

**Comment by numerative** [comment]
Problem starts from Android Pie (and probably in the future versions too).
https://developer.android.com/about/versions/pie/android-9.0-changes-28#fg-svc

**Comment by piedcipher** [comment]
I thought 28 was Oreo, Got it! @numerative :+1: Thank you for fixing the issue @s3rius :wrench:
